# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
addons:
  apt:
    packages:
      - libgconf-2-4
      - xvfb
      - libgtk-3-0
      - inkscape
      - poppler-utils

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - xvfb-run julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
